### ISSUE TITLE
Can I use your code?

### ISSUE THREAD

**Issue by Sakura0721** [MinLL/GameInterfaceForToys#14]
Hey bro, I want to integrate `coyote` into another game `VRChat`, I want to use your code `dg_interface.py` and `dg_encoding.py` in my project. However, I don't find any License file in this repo.

So I open this issue to ask if I can use your code in my project?

**Comment by inertaert** [comment]
Hello,

I am the originator of the two files in question (with Min having done most of the work integrating them into GIFT proper) and can confirm that they are indeed covered by the MIT license. The license is shown at the top of each file.

You are free to use the code as you please. I also invite you to share your project. Coyote support for VRChat sounds exciting. ;)

By the way, does the MIT license cover the whole of GIFT too, @MinLL ?

Cheers.

**Comment by Sakura0721** [comment]
Great! Thanks to your work on Bluetooth protocol of Coyote!

Here's my project about VRC: https://github.com/Sakura0721/osc-toys

**Comment by MinLL** [comment]
Hey @Sakura0721 - Thanks for reaching out. As @inertaert mentioned, there's no problem with you using those files for your own project.

@inertaert Hmm! I hadn't really thought about licensing too much. I'll get back to you on that. I'm not really concerned if people want to use my/our code for their own projects. It's nice to give back to the community in that way. It'd be cool to know who was doing it, though.
